default:
  tags:
    - shell

stages:
  - deploy

variables:
  URL_PROD: "http://example"
  TEST_ENV_URL: $URL_PROD


deploy_review:
  stage: deploy
  environment:
    name: production
    url: $URL_PROD
    on_stop: stop_review
  script:
    - echo $TEST_ENV_URL
    - docker-compose up -d
  only:
    - master

stop_review:
  stage: deploy
  environment:
    name: production
    action: stop
  script:
    - docker-compose down
  when: manual
