default:
  tags:
    - shell

stages:
  - build
  - deploy

variables:
  URL_PROD: "http://example"

build:
  stage: build
  before_script:
    - git submodule sync && git submodule update --init
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - master

include: '/docker/.gitlab-ci-deploy.yml'
