default:
  tags:
    - shell

stages:
  - deploy

variables:
  URL_PROD: "http://example"


deploy:
  stage: deploy
  environment:
    name: production
    url: $URL_PROD
    on_stop: stop_review
  script:
    - docker-compose up -d
  only:
    - master

stop_review:
  stage: deploy
  script:
    - docker-compose down
  environment:
    name: production
    action: stop
