default:
  tags:
    - shell

stages:
  - build
  - deploy

variables:
  URL_PROD: "http://example"

.before_script_gitlabdocker:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  extends: .before_script_gitlabdocker
  before_script:
    - git submodule sync && git submodule update --init
  script:
    - docker-compose build
  only:
    - master

include: '/docker/.gitlab-ci-deploy.yml'
